[package]
name = "microsoft_botframework"
version = "0.1.0"
authors = ["Peter Glotfelty 🚀"]
edition = "2018"

[dependencies]
actix-web = "*"
actix = "*"
futures = "0.1"
serde_json = "*"
strum = "*"
nom = "*"
jsonwebtoken = "*"

[dev-dependencies]
strum_macros = "*"